server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: auto-simple-agent
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/agentx
    username: postgres
    password: postgres
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.feynix.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

# LLM服务配置
llm:
  provider:
    default: ${LLM_DEFAULT_PROVIDER:siliconflow}
    providers:
      siliconflow:
        name: SiliconFlow
        api-url: ${SILICONFLOW_API_URL:https://api.siliconflow.cn/v1/chat/completions}
        api-key: ${SILICONFLOW_API_KEY:}
        model: ${SILICONFLOW_MODEL:Qwen/Qwen2.5-VL-72B-Instruct}
        timeout: ${SILICONFLOW_TIMEOUT:30000}


logging:
  level:
    root: info
    org.feynix: debug
  file:
    name: logs/auto-simple-agent.log
